In [46]:
import pytz
import datetime
import numpy
import pandas

In [47]:
import time

In [49]:
start = datetime.datetime(year=2020, month=1, day=1, hour=0, minute=0, second=0, microsecond=0, tzinfo=pytz.timezone('EST'))
end = datetime.datetime(year=2020, month=5, day=1, hour=0, minute=0, second=0, microsecond=0, tzinfo=pytz.timezone('EST'))
test_range = pandas.DataFrame(data=pandas.date_range(start=start, end=end, freq='D'), columns=['base'])
test_range

                         base
0   2020-01-01 00:00:00-05:00
1   2020-01-02 00:00:00-05:00
2   2020-01-03 00:00:00-05:00
3   2020-01-04 00:00:00-05:00
4   2020-01-05 00:00:00-05:00
..                        ...
117 2020-04-27 00:00:00-05:00
118 2020-04-28 00:00:00-05:00
119 2020-04-29 00:00:00-05:00
120 2020-04-30 00:00:00-05:00
121 2020-05-01 00:00:00-05:00

[122 rows x 1 columns]

In [31]:
from busy_exchange.utils import BusyDayExchange

In [4]:
test_range['is_holi'] = test_range['base'].apply(func=BusyDayExchange.is_holi)
test_range['is_full'] = test_range['base'].apply(func=BusyDayExchange.is_full)
test_range['is_cut'] = test_range['base'].apply(func=BusyDayExchange.is_cut)
test_range

                         base is_holi is_full is_cut
0   2020-01-01 00:00:00-05:00    True   False  False
1   2020-01-02 00:00:00-05:00   False    True  False
2   2020-01-03 00:00:00-05:00   False    True  False
3   2020-01-04 00:00:00-05:00   False    True  False
4   2020-01-05 00:00:00-05:00   False    True  False
..                        ...     ...     ...    ...
117 2020-04-27 00:00:00-05:00   False    True  False
118 2020-04-28 00:00:00-05:00   False    True  False
119 2020-04-29 00:00:00-05:00   False    True  False
120 2020-04-30 00:00:00-05:00   False    True  False
121 2020-05-01 00:00:00-05:00   False    True  False

[122 rows x 4 columns]

In [50]:
run_time = time.time()
test_range['to_holi'] = test_range['base'].apply(func=BusyDayExchange.to_holiday, args=(True,))
test_range['to_full'] = test_range['base'].apply(func=BusyDayExchange.to_fullday, args=(True,))
test_range['to_cut'] = test_range['base'].apply(func=BusyDayExchange.to_cutday, args=(True,))
test_range['af_holi'] = test_range['base'].apply(func=BusyDayExchange.to_holiday, args=(False,))
test_range['af_full'] = test_range['base'].apply(func=BusyDayExchange.to_fullday, args=(False,))
test_range['af_cut'] = test_range['base'].apply(func=BusyDayExchange.to_cutday, args=(False,))
run_time = time.time() - run_time
print(run_time)
test_range

13.71179723739624

,base,to_holi,to_full,to_cut,af_holi,af_full,af_cut
0,2020-01-01 00:00:00-05:00,19,1,331,-7,-1,-8
1,2020-01-02 00:00:00-05:00,18,1,330,-1,-2,-9
2,2020-01-03 00:00:00-05:00,17,1,329,-2,-1,-10
3,2020-01-04 00:00:00-05:00,16,1,328,-3,-1,-11
4,2020-01-05 00:00:00-05:00,15,1,327,-4,-1,-12
...,...,...,...,...,...,...,...
117,2020-04-27 00:00:00-05:00,28,1,214,-17,-1,-125
118,2020-04-28 00:00:00-05:00,27,1,213,-18,-1,-126
119,2020-04-29 00:00:00-05:00,26,1,212,-19,-1,-127
120,2020-04-30 00:00:00-05:00,25,1,211,-20,-1,-128
121,2020-05-01 00:00:00-05:00,24,1,210,-21,-1,-129

In [6]:
from busy_exchange.utils import BusyTimeExchange

In [7]:
test_range['to_open'] = test_range['base'].apply(func=BusyTimeExchange.to_open)
test_range['to_close'] = test_range['base'].apply(func=BusyTimeExchange.to_close)
test_range

,base,is_holi,is_full,is_cut,to_holi,to_full,to_cut,af_holi,af_full,af_cut,to_open,to_close
0,2020-01-01 00:00:00-05:00,True,False,False,19,1,331,-7,-1,-8,<NA>,<NA>
1,2020-01-02 00:00:00-05:00,False,True,False,18,1,330,-1,-2,-9,-52200,-28800
2,2020-01-03 00:00:00-05:00,False,True,False,17,1,329,-2,-1,-10,-138600,-115200
3,2020-01-04 00:00:00-05:00,False,True,False,16,1,328,-3,-1,-11,-225000,-201600
4,2020-01-05 00:00:00-05:00,False,True,False,15,1,327,-4,-1,-12,-311400,-288000
...,...,...,...,...,...,...,...,...,...,...,...,...
117,2020-04-27 00:00:00-05:00,False,True,False,28,1,214,-17,-1,-125,-1.953e+06,-1.9296e+06
118,2020-04-28 00:00:00-05:00,False,True,False,27,1,213,-18,-1,-126,-2.0394e+06,-2.016e+06
119,2020-04-29 00:00:00-05:00,False,True,False,26,1,212,-19,-1,-127,-2.1258e+06,-2.1024e+06
120,2020-04-30 00:00:00-05:00,False,True,False,25,1,211,-20,-1,-128,-2.2122e+06,-2.1888e+06
121,2020-05-01 00:00:00-05:00,False,True,False,24,1,210,-21,-1,-129,379800,403200

In [2]:
d = './dataset.csv'
data = pandas.read_csv(d)
data

,ticker,time,open_LAG0,close_LAG0,high_LAG0,low_LAG0,volume_LAG0,open_LAG1,close_LAG1,high_LAG1,...,volume_LAG99,open_LAG100,close_LAG100,high_LAG100,low_LAG100,volume_LAG100,id,title,lag,news_time
0,MSFT,2019-09-23 15:53:00+00:00,-0.000359,0.000072,-0.000287,-0.000144,-0.370970,-0.000143,-0.000430,-0.000143,...,0.156438,0.000144,0.000361,0.000505,0.000217,-0.140647,244575,"""Flash Boys"" exchange IEX drops out of corpora...",1,2019-09-23 15:52:00+00:00
1,MSFT,2019-09-23 15:54:00+00:00,0.000144,0.000359,0.000502,0.000359,-0.138693,-0.000359,0.000072,-0.000287,...,-0.194598,0.000361,0.000577,0.000361,0.000361,0.156438,244575,"""Flash Boys"" exchange IEX drops out of corpora...",2,2019-09-23 15:52:00+00:00
2,MSFT,2019-09-23 15:55:00+00:00,0.000287,0.000215,0.000072,0.000215,-0.160793,0.000144,0.000359,0.000502,...,0.319666,0.000577,0.000433,0.000649,0.000505,-0.194598,244575,"""Flash Boys"" exchange IEX drops out of corpora...",3,2019-09-23 15:52:00+00:00
3,MSFT,2019-09-23 15:56:00+00:00,0.000287,0.000000,0.000215,0.000143,0.691880,0.000287,0.000215,0.000072,...,-0.100533,0.000577,0.000721,0.000648,0.000649,0.319666,244575,"""Flash Boys"" exchange IEX drops out of corpora...",4,2019-09-23 15:52:00+00:00
4,MSFT,2019-09-23 15:57:00+00:00,-0.000072,-0.000143,-0.000143,0.000000,-0.357331,0.000287,0.000000,0.000215,...,-0.415248,0.000576,0.000504,0.000648,0.000576,-0.100533,244575,"""Flash Boys"" exchange IEX drops out of corpora...",5,2019-09-23 15:52:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163920,MSFT,2019-09-23 16:38:00+00:00,0.000359,0.000000,0.000072,0.000287,-0.334942,0.000359,0.000287,0.000359,...,0.247223,0.000504,-0.000072,-0.000072,0.000288,-0.568541,243148,"‘When the president does it, that means it’s n...",95,2019-09-23 15:03:00+00:00
163921,MSFT,2019-09-23 16:39:00+00:00,-0.000072,0.000072,0.000000,0.000000,-0.090493,0.000359,0.000000,0.000072,...,1.175953,-0.000072,0.000504,0.000288,0.000216,0.247223,243148,"‘When the president does it, that means it’s n...",96,2019-09-23 15:03:00+00:00
163922,MSFT,2019-09-23 16:40:00+00:00,0.000072,-0.000215,-0.000072,-0.000144,1.270361,-0.000072,0.000072,0.000000,...,-0.529884,0.000576,0.000072,0.000504,0.000216,1.175953,243148,"‘When the president does it, that means it’s n...",97,2019-09-23 15:03:00+00:00
163923,MSFT,2019-09-23 16:41:00+00:00,-0.000215,0.000574,0.000359,0.000000,0.039201,0.000072,-0.000215,-0.000072,...,-0.188079,0.000000,0.000000,-0.000431,0.000000,-0.529884,243148,"‘When the president does it, that means it’s n...",98,2019-09-23 15:03:00+00:00
163924,MSFT,2019-09-23 16:42:00+00:00,0.000574,0.000143,0.000215,0.000574,-0.232562,-0.000215,0.000574,0.000359,...,2.003987,0.000072,0.000719,0.000791,0.000360,-0.188079,243148,"‘When the president does it, that means it’s n...",99,2019-09-23 15:03:00+00:00

In [3]:
target_day = pandas.to_datetime(datetime.datetime(year=2019, month=9, day=3, tzinfo=pytz.timezone('UTC')))
target_day

Timestamp('2019-09-03 00:00:00+0000', tz='UTC')

In [4]:
data[data['time'] == target_day]

Empty DataFrame
Columns: [ticker, time, open_LAG0, close_LAG0, high_LAG0, low_LAG0, volume_LAG0, open_LAG1, close_LAG1, high_LAG1, low_LAG1, volume_LAG1, open_LAG2, close_LAG2, high_LAG2, low_LAG2, volume_LAG2, open_LAG3, close_LAG3, high_LAG3, low_LAG3, volume_LAG3, open_LAG4, close_LAG4, high_LAG4, low_LAG4, volume_LAG4, open_LAG5, close_LAG5, high_LAG5, low_LAG5, volume_LAG5, open_LAG6, close_LAG6, high_LAG6, low_LAG6, volume_LAG6, open_LAG7, close_LAG7, high_LAG7, low_LAG7, volume_LAG7, open_LAG8, close_LAG8, high_LAG8, low_LAG8, volume_LAG8, open_LAG9, close_LAG9, high_LAG9, low_LAG9, volume_LAG9, open_LAG10, close_LAG10, high_LAG10, low_LAG10, volume_LAG10, open_LAG11, close_LAG11, high_LAG11, low_LAG11, volume_LAG11, open_LAG12, close_LAG12, high_LAG12, low_LAG12, volume_LAG12, open_LAG13, close_LAG13, high_LAG13, low_LAG13, volume_LAG13, open_LAG14, close_LAG14, high_LAG14, low_LAG14, volume_LAG14, open_LAG15, close_LAG15, high_LAG15, low_LAG15, volume_LAG15, open_LAG16, close_LAG16, high_LAG16, low_LAG16, volume_LAG16, open_LAG17, close_LAG17, high_LAG17, low_LAG17, volume_LAG17, open_LAG18, close_LAG18, high_LAG18, low_LAG18, volume_LAG18, open_LAG19, close_LAG19, high_LAG19, ...]
Index: []

[0 rows x 511 columns]

In [7]:
numpy.unique(data['time'].values).tolist()

['2019-08-30 15:08:00+00:00',
 '2019-08-30 15:09:00+00:00',
 '2019-08-30 15:10:00+00:00',
 '2019-08-30 15:11:00+00:00',
 '2019-08-30 15:12:00+00:00',
 '2019-08-30 15:13:00+00:00',
 '2019-08-30 15:14:00+00:00',
 '2019-08-30 15:15:00+00:00',
 '2019-08-30 15:16:00+00:00',
 '2019-08-30 15:17:00+00:00',
 '2019-08-30 15:18:00+00:00',
 '2019-08-30 15:19:00+00:00',
 '2019-08-30 15:20:00+00:00',
 '2019-08-30 15:21:00+00:00',
 '2019-08-30 15:22:00+00:00',
 '2019-08-30 15:23:00+00:00',
 '2019-08-30 15:24:00+00:00',
 '2019-08-30 15:25:00+00:00',
 '2019-08-30 15:26:00+00:00',
 '2019-08-30 15:27:00+00:00',
 '2019-08-30 15:28:00+00:00',
 '2019-08-30 15:29:00+00:00',
 '2019-08-30 15:30:00+00:00',
 '2019-08-30 15:31:00+00:00',
 '2019-08-30 15:32:00+00:00',
 '2019-08-30 15:33:00+00:00',
 '2019-08-30 15:34:00+00:00',
 '2019-08-30 15:35:00+00:00',
 '2019-08-30 15:36:00+00:00',
 '2019-08-30 15:37:00+00:00',
 '2019-08-30 15:38:00+00:00',
 '2019-08-30 15:39:00+00:00',
 '2019-08-30 15:40:00+00:00',
 '2019-08-30 15:41:00+00:00',
 '2019-08-30 15:42:00+00:00',
 '2019-08-30 15:43:00+00:00',
 '2019-08-30 15:44:00+00:00',
 '2019-08-30 15:45:00+00:00',
 '2019-08-30 15:46:00+00:00',
 '2019-08-30 15:47:00+00:00',
 '2019-08-30 15:48:00+00:00',
 '2019-08-30 15:49:00+00:00',
 '2019-08-30 15:50:00+00:00',
 '2019-08-30 15:51:00+00:00',
 '2019-08-30 15:52:00+00:00',
 '2019-08-30 15:53:00+00:00',
 '2019-08-30 15:54:00+00:00',
 '2019-08-30 15:55:00+00:00',
 '2019-08-30 15:56:00+00:00',
 '2019-08-30 15:57:00+00:00',
 '2019-08-30 15:58:00+00:00',
 '2019-08-30 15:59:00+00:00',
 '2019-08-30 16:00:00+00:00',
 '2019-08-30 16:01:00+00:00',
 '2019-08-30 16:02:00+00:00',
 '2019-08-30 16:03:00+00:00',
 '2019-08-30 16:04:00+00:00',
 '2019-08-30 16:05:00+00:00',
 '2019-08-30 16:06:00+00:00',
 '2019-08-30 16:07:00+00:00',
 '2019-08-30 16:08:00+00:00',
 '2019-08-30 16:09:00+00:00',
 '2019-08-30 16:10:00+00:00',
 '2019-08-30 16:11:00+00:00',
 '2019-08-30 16:12:00+00:00',
 '2019-08-30 16:13:00+00:00',
 '2019-08-30 16:14:00+00:00',
 '2019-08-30 16:15:00+00:00',
 '2019-08-30 16:16:00+00:00',
 '2019-08-30 16:17:00+00:00',
 '2019-08-30 16:18:00+00:00',
 '2019-08-30 16:19:00+00:00',
 '2019-08-30 16:20:00+00:00',
 '2019-08-30 16:21:00+00:00',
 '2019-08-30 16:22:00+00:00',
 '2019-08-30 16:23:00+00:00',
 '2019-08-30 16:24:00+00:00',
 '2019-08-30 16:25:00+00:00',
 '2019-08-30 16:26:00+00:00',
 '2019-08-30 16:27:00+00:00',
 '2019-08-30 16:28:00+00:00',
 '2019-08-30 16:29:00+00:00',
 '2019-08-30 16:30:00+00:00',
 '2019-08-30 16:31:00+00:00',
 '2019-08-30 16:32:00+00:00',
 '2019-08-30 16:33:00+00:00',
 '2019-08-30 16:34:00+00:00',
 '2019-08-30 16:35:00+00:00',
 '2019-08-30 16:36:00+00:00',
 '2019-08-30 16:37:00+00:00',
 '2019-08-30 16:38:00+00:00',
 '2019-08-30 16:39:00+00:00',
 '2019-08-30 16:40:00+00:00',
 '2019-08-30 16:41:00+00:00',
 '2019-08-30 16:42:00+00:00',
 '2019-08-30 16:43:00+00:00',
 '2019-08-30 16:44:00+00:00',
 '2019-08-30 16:45:00+00:00',
 '2019-08-30 16:46:00+00:00',
 '2019-08-30 16:47:00+00:00',
 '2019-08-30 16:48:00+00:00',
 '2019-08-30 16:49:00+00:00',
 '2019-08-30 16:50:00+00:00',
 '2019-08-30 16:51:00+00:00',
 '2019-08-30 16:52:00+00:00',
 '2019-08-30 16:53:00+00:00',
 '2019-08-30 16:54:00+00:00',
 '2019-08-30 16:55:00+00:00',
 '2019-08-30 16:56:00+00:00',
 '2019-08-30 16:57:00+00:00',
 '2019-08-30 16:58:00+00:00',
 '2019-08-30 16:59:00+00:00',
 '2019-08-30 17:00:00+00:00',
 '2019-08-30 17:01:00+00:00',
 '2019-08-30 17:02:00+00:00',
 '2019-08-30 17:03:00+00:00',
 '2019-08-30 17:04:00+00:00',
 '2019-08-30 17:05:00+00:00',
 '2019-08-30 17:06:00+00:00',
 '2019-08-30 17:07:00+00:00',
 '2019-08-30 17:08:00+00:00',
 '2019-08-30 17:09:00+00:00',
 '2019-08-30 17:10:00+00:00',
 '2019-08-30 17:11:00+00:00',
 '2019-08-30 17:12:00+00:00',
 '2019-08-30 17:13:00+00:00',
 '2019-08-30 17:14:00+00:00',
 '2019-08-30 17:15:00+00:00',
 '2019-08-30 17:16:00+00:00',
 '2019-08-30 17:17:00+00:00',
 '2019-08-30 17:18:00+00:00',
 '2019-08-30 17:19:00+00:00',
 '2019-08-30 17:20:00+00:00',
 '2019-08-30 17:21:00+00:00',
 '2019-08-30 17:22:00+00:00',
 '2019-08-30 17:23:00+00:00',
 '2019-08-30 17:24:00+00:00',
 '2019-08-30 17:25:00+00:00',
 '2019-08-30 17:26:00+00:00',
 '2019-08-30 17:27:00+00:00',
 '2019-08-30 17:28:00+00:00',
 '2019-08-30 17:29:00+00:00',
 '2019-08-30 17:30:00+00:00',
 '2019-08-30 17:31:00+00:00',
 '2019-08-30 17:32:00+00:00',
 '2019-08-30 17:33:00+00:00',
 '2019-08-30 17:34:00+00:00',
 '2019-08-30 17:35:00+00:00',
 '2019-08-30 17:36:00+00:00',
 '2019-08-30 17:37:00+00:00',
 '2019-08-30 17:38:00+00:00',
 '2019-08-30 17:39:00+00:00',
 '2019-08-30 17:40:00+00:00',
 '2019-08-30 17:41:00+00:00',
 '2019-08-30 17:42:00+00:00',
 '2019-08-30 17:43:00+00:00',
 '2019-08-30 17:44:00+00:00',
 '2019-08-30 17:45:00+00:00',
 '2019-08-30 17:46:00+00:00',
 '2019-08-30 17:47:00+00:00',
 '2019-08-30 17:48:00+00:00',
 '2019-08-30 17:49:00+00:00',
 '2019-08-30 17:50:00+00:00',
 '2019-08-30 17:51:00+00:00',
 '2019-08-30 17:52:00+00:00',
 '2019-08-30 17:53:00+00:00',
 '2019-08-30 17:54:00+00:00',
 '2019-08-30 17:55:00+00:00',
 '2019-08-30 17:56:00+00:00',
 '2019-08-30 17:57:00+00:00',
 '2019-08-30 17:58:00+00:00',
 '2019-08-30 17:59:00+00:00',
 '2019-08-30 18:00:00+00:00',
 '2019-08-30 18:01:00+00:00',
 '2019-08-30 18:02:00+00:00',
 '2019-08-30 18:03:00+00:00',
 '2019-08-30 18:04:00+00:00',
 '2019-08-30 18:05:00+00:00',
 '2019-08-30 18:06:00+00:00',
 '2019-08-30 18:07:00+00:00',
 '2019-08-30 18:08:00+00:00',
 '2019-08-30 18:09:00+00:00',
 '2019-08-30 18:10:00+00:00',
 '2019-08-30 18:11:00+00:00',
 '2019-08-30 18:12:00+00:00',
 '2019-08-30 18:13:00+00:00',
 '2019-08-30 18:14:00+00:00',
 '2019-08-30 18:15:00+00:00',
 '2019-08-30 18:16:00+00:00',
 '2019-08-30 18:17:00+00:00',
 '2019-08-30 18:18:00+00:00',
 '2019-08-30 18:19:00+00:00',
 '2019-08-30 18:20:00+00:00',
 '2019-08-30 18:21:00+00:00',
 '2019-08-30 18:22:00+00:00',
 '2019-08-30 18:23:00+00:00',
 '2019-08-30 18:24:00+00:00',
 '2019-08-30 18:25:00+00:00',
 '2019-08-30 18:26:00+00:00',
 '2019-08-30 18:27:00+00:00',
 '2019-08-30 18:28:00+00:00',
 '2019-08-30 18:29:00+00:00',
 '2019-08-30 18:30:00+00:00',
 '2019-08-30 18:31:00+00:00',
 '2019-08-30 18:32:00+00:00',
 '2019-08-30 18:33:00+00:00',
 '2019-08-30 18:34:00+00:00',
 '2019-08-30 18:35:00+00:00',
 '2019-08-30 18:36:00+00:00',
 '2019-08-30 18:37:00+00:00',
 '2019-08-30 18:38:00+00:00',
 '2019-08-30 18:39:00+00:00',
 '2019-08-30 18:40:00+00:00',
 '2019-08-30 18:41:00+00:00',
 '2019-08-30 18:42:00+00:00',
 '2019-08-30 18:43:00+00:00',
 '2019-08-30 18:44:00+00:00',
 '2019-08-30 18:45:00+00:00',
 '2019-08-30 18:46:00+00:00',
 '2019-08-30 18:47:00+00:00',
 '2019-08-30 18:48:00+00:00',
 '2019-08-30 18:49:00+00:00',
 '2019-08-30 18:50:00+00:00',
 '2019-08-30 18:51:00+00:00',
 '2019-08-30 18:52:00+00:00',
 '2019-08-30 18:53:00+00:00',
 '2019-08-30 18:54:00+00:00',
 '2019-08-30 18:55:00+00:00',
 '2019-08-30 18:56:00+00:00',
 '2019-08-30 18:57:00+00:00',
 '2019-08-30 18:58:00+00:00',
 '2019-08-30 18:59:00+00:00',
 '2019-08-30 19:00:00+00:00',
 '2019-08-30 19:01:00+00:00',
 '2019-08-30 19:02:00+00:00',
 '2019-08-30 19:03:00+00:00',
 '2019-08-30 19:04:00+00:00',
 '2019-08-30 19:05:00+00:00',
 '2019-08-30 19:06:00+00:00',
 '2019-08-30 19:07:00+00:00',
 '2019-08-30 19:08:00+00:00',
 '2019-08-30 19:09:00+00:00',
 '2019-08-30 19:10:00+00:00',
 '2019-08-30 19:11:00+00:00',
 '2019-08-30 19:12:00+00:00',
 '2019-08-30 19:13:00+00:00',
 '2019-08-30 19:14:00+00:00',
 '2019-08-30 19:15:00+00:00',
 '2019-08-30 19:16:00+00:00',
 '2019-08-30 19:17:00+00:00',
 '2019-08-30 19:18:00+00:00',
 '2019-08-30 19:19:00+00:00',
 '2019-08-30 19:20:00+00:00',
 '2019-08-30 19:21:00+00:00',
 '2019-08-30 19:22:00+00:00',
 '2019-08-30 19:23:00+00:00',
 '2019-08-30 19:24:00+00:00',
 '2019-08-30 19:25:00+00:00',
 '2019-08-30 19:26:00+00:00',
 '2019-08-30 19:27:00+00:00',
 '2019-08-30 19:28:00+00:00',
 '2019-08-30 19:29:00+00:00',
 '2019-08-30 19:30:00+00:00',
 '2019-08-30 19:31:00+00:00',
 '2019-08-30 19:32:00+00:00',
 '2019-08-30 19:33:00+00:00',
 '2019-08-30 19:34:00+00:00',
 '2019-08-30 19:35:00+00:00',
 '2019-08-30 19:36:00+00:00',
 '2019-08-30 19:37:00+00:00',
 '2019-08-30 19:38:00+00:00',
 '2019-08-30 19:39:00+00:00',
 '2019-08-30 19:40:00+00:00',
 '2019-08-30 19:41:00+00:00',
 '2019-08-30 19:42:00+00:00',
 '2019-08-30 19:43:00+00:00',
 '2019-08-30 19:44:00+00:00',
 '2019-08-30 19:45:00+00:00',
 '2019-08-30 19:46:00+00:00',
 '2019-08-30 19:47:00+00:00',
 '2019-08-30 19:48:00+00:00',
 '2019-08-30 19:49:00+00:00',
 '2019-08-30 19:50:00+00:00',
 '2019-08-30 19:51:00+00:00',
 '2019-08-30 19:52:00+00:00',
 '2019-08-30 19:53:00+00:00',
 '2019-08-30 19:54:00+00:00',
 '2019-08-30 19:55:00+00:00',
 '2019-08-30 19:56:00+00:00',
 '2019-08-30 19:57:00+00:00',
 '2019-08-30 19:58:00+00:00',
 '2019-08-30 19:59:00+00:00',
 '2019-08-30 20:00:00+00:00',
 '2019-08-30 20:01:00+00:00',
 '2019-08-30 20:02:00+00:00',
 '2019-08-30 20:03:00+00:00',
 '2019-08-30 20:04:00+00:00',
 '2019-08-30 20:05:00+00:00',
 '2019-08-30 20:06:00+00:00',
 '2019-09-23 15:07:00+00:00',
 '2019-09-23 15:08:00+00:00',
 '2019-09-23 15:09:00+00:00',
 '2019-09-23 15:10:00+00:00',
 '2019-09-23 15:11:00+00:00',
 '2019-09-23 15:12:00+00:00',
 '2019-09-23 15:13:00+00:00',
 '2019-09-23 15:14:00+00:00',
 '2019-09-23 15:15:00+00:00',
 '2019-09-23 15:16:00+00:00',
 '2019-09-23 15:17:00+00:00',
 '2019-09-23 15:18:00+00:00',
 '2019-09-23 15:19:00+00:00',
 '2019-09-23 15:20:00+00:00',
 '2019-09-23 15:21:00+00:00',
 '2019-09-23 15:22:00+00:00',
 '2019-09-23 15:23:00+00:00',
 '2019-09-23 15:24:00+00:00',
 '2019-09-23 15:25:00+00:00',
 '2019-09-23 15:26:00+00:00',
 '2019-09-23 15:27:00+00:00',
 '2019-09-23 15:28:00+00:00',
 '2019-09-23 15:29:00+00:00',
 '2019-09-23 15:30:00+00:00',
 '2019-09-23 15:31:00+00:00',
 '2019-09-23 15:32:00+00:00',
 '2019-09-23 15:33:00+00:00',
 '2019-09-23 15:34:00+00:00',
 '2019-09-23 15:35:00+00:00',
 '2019-09-23 15:36:00+00:00',
 '2019-09-23 15:37:00+00:00',
 '2019-09-23 15:38:00+00:00',
 '2019-09-23 15:39:00+00:00',
 '2019-09-23 15:40:00+00:00',
 '2019-09-23 15:41:00+00:00',
 '2019-09-23 15:42:00+00:00',
 '2019-09-23 15:43:00+00:00',
 '2019-09-23 15:44:00+00:00',
 '2019-09-23 15:45:00+00:00',
 '2019-09-23 15:46:00+00:00',
 '2019-09-23 15:47:00+00:00',
 '2019-09-23 15:48:00+00:00',
 '2019-09-23 15:49:00+00:00',
 '2019-09-23 15:50:00+00:00',
 '2019-09-23 15:51:00+00:00',
 '2019-09-23 15:52:00+00:00',
 '2019-09-23 15:53:00+00:00',
 '2019-09-23 15:54:00+00:00',
 '2019-09-23 15:55:00+00:00',
 '2019-09-23 15:56:00+00:00',
 '2019-09-23 15:57:00+00:00',
 '2019-09-23 15:58:00+00:00',
 '2019-09-23 15:59:00+00:00',
 '2019-09-23 16:00:00+00:00',
 '2019-09-23 16:01:00+00:00',
 '2019-09-23 16:02:00+00:00',
 '2019-09-23 16:03:00+00:00',
 '2019-09-23 16:04:00+00:00',
 '2019-09-23 16:05:00+00:00',
 '2019-09-23 16:06:00+00:00',
 '2019-09-23 16:07:00+00:00',
 '2019-09-23 16:08:00+00:00',
 '2019-09-23 16:09:00+00:00',
 '2019-09-23 16:10:00+00:00',
 '2019-09-23 16:11:00+00:00',
 '2019-09-23 16:12:00+00:00',
 '2019-09-23 16:13:00+00:00',
 '2019-09-23 16:14:00+00:00',
 '2019-09-23 16:15:00+00:00',
 '2019-09-23 16:16:00+00:00',
 '2019-09-23 16:17:00+00:00',
 '2019-09-23 16:18:00+00:00',
 '2019-09-23 16:19:00+00:00',
 '2019-09-23 16:20:00+00:00',
 '2019-09-23 16:21:00+00:00',
 '2019-09-23 16:22:00+00:00',
 '2019-09-23 16:23:00+00:00',
 '2019-09-23 16:24:00+00:00',
 '2019-09-23 16:25:00+00:00',
 '2019-09-23 16:26:00+00:00',
 '2019-09-23 16:27:00+00:00',
 '2019-09-23 16:28:00+00:00',
 '2019-09-23 16:29:00+00:00',
 '2019-09-23 16:30:00+00:00',
 '2019-09-23 16:31:00+00:00',
 '2019-09-23 16:32:00+00:00',
 '2019-09-23 16:33:00+00:00',
 '2019-09-23 16:34:00+00:00',
 '2019-09-23 16:35:00+00:00',
 '2019-09-23 16:36:00+00:00',
 '2019-09-23 16:37:00+00:00',
 '2019-09-23 16:38:00+00:00',
 '2019-09-23 16:39:00+00:00',
 '2019-09-23 16:40:00+00:00',
 '2019-09-23 16:41:00+00:00',
 '2019-09-23 16:42:00+00:00',
 '2019-09-23 16:43:00+00:00',
 '2019-09-23 16:44:00+00:00',
 '2019-09-23 16:45:00+00:00',
 '2019-09-23 16:46:00+00:00',
 '2019-09-23 16:47:00+00:00',
 '2019-09-23 16:48:00+00:00',
 '2019-09-23 16:49:00+00:00',
 '2019-09-23 16:50:00+00:00',
 '2019-09-23 16:51:00+00:00',
 '2019-09-23 16:52:00+00:00',
 '2019-09-23 16:53:00+00:00',
 '2019-09-23 16:54:00+00:00',
 '2019-09-23 16:55:00+00:00',
 '2019-09-23 16:56:00+00:00',
 '2019-09-23 16:57:00+00:00',
 '2019-09-23 16:58:00+00:00',
 '2019-09-23 16:59:00+00:00',
 '2019-09-23 17:00:00+00:00',
 '2019-09-23 17:01:00+00:00',
 '2019-09-23 17:02:00+00:00',
 '2019-09-23 17:03:00+00:00',
 '2019-09-23 17:04:00+00:00',
 '2019-09-23 17:05:00+00:00',
 '2019-09-23 17:06:00+00:00',
 '2019-09-23 17:07:00+00:00',
 '2019-09-23 17:08:00+00:00',
 '2019-09-23 17:09:00+00:00',
 '2019-09-23 17:10:00+00:00',
 '2019-09-23 17:11:00+00:00',
 '2019-09-23 17:12:00+00:00',
 '2019-09-23 17:13:00+00:00',
 '2019-09-23 17:14:00+00:00',
 '2019-09-23 17:15:00+00:00',
 '2019-09-23 17:16:00+00:00',
 '2019-09-23 17:17:00+00:00',
 '2019-09-23 17:18:00+00:00',
 '2019-09-23 17:19:00+00:00',
 '2019-09-23 17:20:00+00:00',
 '2019-09-23 17:21:00+00:00',
 '2019-09-23 17:22:00+00:00',
 '2019-09-23 17:23:00+00:00',
 '2019-09-23 17:24:00+00:00',
 '2019-09-23 17:25:00+00:00',
 '2019-09-23 17:26:00+00:00',
 '2019-09-23 17:27:00+00:00',
 '2019-09-23 17:28:00+00:00',
 '2019-09-23 17:29:00+00:00',
 '2019-09-23 17:30:00+00:00',
 '2019-09-23 17:31:00+00:00',
 '2019-09-23 17:32:00+00:00',
 '2019-09-23 17:33:00+00:00',
 '2019-09-23 17:34:00+00:00',
 '2019-09-23 17:35:00+00:00',
 '2019-09-23 17:36:00+00:00',
 '2019-09-23 17:37:00+00:00',
 '2019-09-23 17:38:00+00:00',
 '2019-09-23 17:39:00+00:00',
 '2019-09-23 17:40:00+00:00',
 '2019-09-23 17:41:00+00:00',
 '2019-09-23 17:42:00+00:00',
 '2019-09-23 17:43:00+00:00',
 '2019-09-23 17:44:00+00:00',
 '2019-09-23 17:45:00+00:00',
 '2019-09-23 17:46:00+00:00',
 '2019-09-23 17:47:00+00:00',
 '2019-09-23 17:48:00+00:00',
 '2019-09-23 17:49:00+00:00',
 '2019-09-23 17:50:00+00:00',
 '2019-09-23 17:51:00+00:00',
 '2019-09-23 17:52:00+00:00',
 '2019-09-23 17:53:00+00:00',
 '2019-09-23 17:54:00+00:00',
 '2019-09-23 17:55:00+00:00',
 '2019-09-23 17:56:00+00:00',
 '2019-09-23 17:57:00+00:00',
 '2019-09-23 17:58:00+00:00',
 '2019-09-23 17:59:00+00:00',
 '2019-09-23 18:00:00+00:00',
 '2019-09-23 18:01:00+00:00',
 '2019-09-23 18:02:00+00:00',
 '2019-09-23 18:03:00+00:00',
 '2019-09-23 18:04:00+00:00',
 '2019-09-23 18:05:00+00:00',
 '2019-09-23 18:06:00+00:00',
 '2019-09-23 18:07:00+00:00',
 '2019-09-23 18:08:00+00:00',
 '2019-09-23 18:09:00+00:00',
 '2019-09-23 18:10:00+00:00',
 '2019-09-23 18:11:00+00:00',
 '2019-09-23 18:12:00+00:00',
 '2019-09-23 18:13:00+00:00',
 '2019-09-23 18:14:00+00:00',
 '2019-09-23 18:15:00+00:00',
 '2019-09-23 18:16:00+00:00',
 '2019-09-23 18:17:00+00:00',
 '2019-09-23 18:18:00+00:00',
 '2019-09-23 18:19:00+00:00',
 '2019-09-23 18:20:00+00:00',
 '2019-09-23 18:21:00+00:00',
 '2019-09-23 18:22:00+00:00',
 '2019-09-23 18:23:00+00:00',
 '2019-09-23 18:24:00+00:00',
 '2019-09-23 18:25:00+00:00',
 '2019-09-23 18:26:00+00:00',
 '2019-09-23 18:27:00+00:00',
 '2019-09-23 18:28:00+00:00',
 '2019-09-23 18:29:00+00:00',
 '2019-09-23 18:30:00+00:00',
 '2019-09-23 18:31:00+00:00',
 '2019-09-23 18:32:00+00:00',
 '2019-09-23 18:33:00+00:00',
 '2019-09-23 18:34:00+00:00',
 '2019-09-23 18:35:00+00:00',
 '2019-09-23 18:36:00+00:00',
 '2019-09-23 18:37:00+00:00',
 '2019-09-23 18:38:00+00:00',
 '2019-09-23 18:39:00+00:00',
 '2019-09-23 18:40:00+00:00',
 '2019-09-23 18:41:00+00:00',
 '2019-09-23 18:42:00+00:00',
 '2019-09-23 18:43:00+00:00',
 '2019-09-23 18:44:00+00:00',
 '2019-09-23 18:45:00+00:00',
 '2019-09-23 18:46:00+00:00',
 '2019-09-23 18:47:00+00:00',
 '2019-09-23 18:48:00+00:00',
 '2019-09-23 18:49:00+00:00',
 '2019-09-23 18:50:00+00:00',
 '2019-09-23 18:51:00+00:00',
 '2019-09-23 18:52:00+00:00',
 '2019-09-23 18:53:00+00:00',
 '2019-09-23 18:54:00+00:00',
 '2019-09-23 18:55:00+00:00',
 '2019-09-23 18:56:00+00:00',
 '2019-09-23 18:57:00+00:00',
 '2019-09-23 18:58:00+00:00',
 '2019-09-23 18:59:00+00:00',
 '2019-09-23 19:00:00+00:00',
 '2019-09-23 19:01:00+00:00',
 '2019-09-23 19:02:00+00:00',
 '2019-09-23 19:03:00+00:00',
 '2019-09-23 19:04:00+00:00',
 '2019-09-23 19:05:00+00:00',
 '2019-09-23 19:06:00+00:00',
 '2019-09-23 19:07:00+00:00',
 '2019-09-23 19:08:00+00:00',
 '2019-09-23 19:09:00+00:00',
 '2019-09-23 19:10:00+00:00',
 '2019-09-23 19:11:00+00:00',
 '2019-09-23 19:12:00+00:00',
 '2019-09-23 19:13:00+00:00',
 '2019-09-23 19:14:00+00:00',
 '2019-09-23 19:15:00+00:00',
 '2019-09-23 19:16:00+00:00',
 '2019-09-23 19:17:00+00:00',
 '2019-09-23 19:18:00+00:00',
 '2019-09-23 19:19:00+00:00',
 '2019-09-23 19:20:00+00:00',
 '2019-09-23 19:21:00+00:00',
 '2019-09-23 19:22:00+00:00',
 '2019-09-23 19:23:00+00:00',
 '2019-09-23 19:24:00+00:00',
 '2019-09-23 19:25:00+00:00',
 '2019-09-23 19:26:00+00:00',
 '2019-09-23 19:27:00+00:00',
 '2019-09-23 19:28:00+00:00',
 '2019-09-23 19:29:00+00:00',
 '2019-09-23 19:30:00+00:00',
 '2019-09-23 19:31:00+00:00',
 '2019-09-23 19:32:00+00:00',
 '2019-09-23 19:33:00+00:00',
 '2019-09-23 19:34:00+00:00',
 '2019-09-23 19:35:00+00:00',
 '2019-09-23 19:36:00+00:00',
 '2019-09-23 19:37:00+00:00',
 '2019-09-23 19:38:00+00:00',
 '2019-09-23 19:39:00+00:00',
 '2019-09-23 19:40:00+00:00',
 '2019-09-23 19:41:00+00:00',
 '2019-09-23 19:42:00+00:00',
 '2019-09-23 19:43:00+00:00',
 '2019-09-23 19:44:00+00:00',
 '2019-09-23 19:45:00+00:00',
 '2019-09-23 19:46:00+00:00',
 '2019-09-23 19:47:00+00:00',
 '2019-09-23 19:48:00+00:00',
 '2019-09-23 19:49:00+00:00',
 '2019-09-23 19:50:00+00:00',
 '2019-09-23 19:51:00+00:00',
 '2019-09-23 19:52:00+00:00',
 '2019-09-23 19:53:00+00:00',
 '2019-09-23 19:54:00+00:00',
 '2019-09-23 19:55:00+00:00',
 '2019-09-23 19:56:00+00:00',
 '2019-09-23 19:57:00+00:00',
 '2019-09-23 19:58:00+00:00',
 '2019-09-23 19:59:00+00:00',
 '2019-09-23 20:00:00+00:00',
 '2019-09-23 20:01:00+00:00',
 '2019-09-23 20:02:00+00:00',
 '2019-09-23 20:03:00+00:00',
 '2019-09-23 20:04:00+00:00',
 '2019-09-24 15:07:00+00:00',
 '2019-09-24 15:08:00+00:00',
 '2019-09-24 15:09:00+00:00',
 '2019-09-24 15:10:00+00:00',
 '2019-09-24 15:11:00+00:00',
 '2019-09-24 15:12:00+00:00',
 '2019-09-24 15:13:00+00:00',
 '2019-09-24 15:14:00+00:00',
 '2019-09-24 15:15:00+00:00',
 '2019-09-24 15:16:00+00:00',
 '2019-09-24 15:17:00+00:00',
 '2019-09-24 15:18:00+00:00',
 '2019-09-24 15:19:00+00:00',
 '2019-09-24 15:20:00+00:00',
 '2019-09-24 15:21:00+00:00',
 '2019-09-24 15:22:00+00:00',
 '2019-09-24 15:23:00+00:00',
 '2019-09-24 15:24:00+00:00',
 '2019-09-24 15:25:00+00:00',
 '2019-09-24 15:26:00+00:00',
 '2019-09-24 15:27:00+00:00',
 '2019-09-24 15:28:00+00:00',
 '2019-09-24 15:29:00+00:00',
 '2019-09-24 15:30:00+00:00',
 '2019-09-24 15:31:00+00:00',
 '2019-09-24 15:32:00+00:00',
 '2019-09-24 15:33:00+00:00',
 '2019-09-24 15:34:00+00:00',
 '2019-09-24 15:35:00+00:00',
 '2019-09-24 15:36:00+00:00',
 '2019-09-24 15:37:00+00:00',
 '2019-09-24 15:38:00+00:00',
 '2019-09-24 15:39:00+00:00',
 '2019-09-24 15:40:00+00:00',
 '2019-09-24 15:41:00+00:00',
 '2019-09-24 15:42:00+00:00',
 '2019-09-24 15:43:00+00:00',
 '2019-09-24 15:44:00+00:00',
 '2019-09-24 15:45:00+00:00',
 '2019-09-24 15:46:00+00:00',
 '2019-09-24 15:47:00+00:00',
 '2019-09-24 15:48:00+00:00',
 '2019-09-24 15:49:00+00:00',
 '2019-09-24 15:50:00+00:00',
 '2019-09-24 15:51:00+00:00',
 '2019-09-24 15:52:00+00:00',
 '2019-09-24 15:53:00+00:00',
 '2019-09-24 15:54:00+00:00',
 '2019-09-24 15:55:00+00:00',
 '2019-09-24 15:56:00+00:00',
 '2019-09-24 15:57:00+00:00',
 '2019-09-24 15:58:00+00:00',
 '2019-09-24 15:59:00+00:00',
 '2019-09-24 16:00:00+00:00',
 '2019-09-24 16:01:00+00:00',
 '2019-09-24 16:02:00+00:00',
 '2019-09-24 16:03:00+00:00',
 '2019-09-24 16:04:00+00:00',
 '2019-09-24 16:05:00+00:00',
 '2019-09-24 16:06:00+00:00',
 '2019-09-24 16:07:00+00:00',
 '2019-09-24 16:08:00+00:00',
 '2019-09-24 16:09:00+00:00',
 '2019-09-24 16:10:00+00:00',
 '2019-09-24 16:11:00+00:00',
 '2019-09-24 16:12:00+00:00',
 '2019-09-24 16:13:00+00:00',
 '2019-09-24 16:14:00+00:00',
 '2019-09-24 16:15:00+00:00',

In [9]:
from tinkoff_api.quotes_loader import call_them_all

In [10]:
k = 'C:/Users/MainUser/Desktop/OpenAPI_sandbox.txt'
crs = open(k, "r")
for columns in (raw.strip().split() for raw in crs):
    api_key = columns[0]

In [14]:
tickers = ['MSFT']
start_date = pandas.to_datetime('2020-01-01')
end_date = pandas.to_datetime('2020-03-01')
token = api_key

In [15]:
result = await call_them_all(tickers, start_date, end_date, token)
result

                         time    open   close    high     low volume ticker
0   2020-01-02 07:00:00+00:00  159.00  159.00  159.00  159.00      2   MSFT
0   2020-01-02 07:03:00+00:00  158.35  158.35  158.35  158.35      1   MSFT
0   2020-01-02 07:06:00+00:00  158.42  158.56  158.56  158.42      2   MSFT
0   2020-01-02 07:07:00+00:00  158.56  158.56  158.56  158.56      7   MSFT
0   2020-01-02 07:08:00+00:00  158.56  158.56  158.56  158.56     40   MSFT
..                        ...     ...     ...     ...     ...    ...    ...
0   2020-02-28 22:39:00+00:00  163.00  163.15  163.15  163.00      6   MSFT
0   2020-02-28 22:40:00+00:00  163.15  163.15  163.15  163.15     39   MSFT
0   2020-02-28 22:41:00+00:00  163.15  163.20  163.20  162.90    312   MSFT
0   2020-02-28 22:42:00+00:00  163.30  163.30  163.30  163.30     10   MSFT
0   2020-02-28 22:43:00+00:00  163.00  163.00  163.00  163.00      1   MSFT

[32259 rows x 7 columns]

In [16]:
def dayi(x):
    return (x.day == 2 and x.month == 1)

In [18]:
result[result['time'].apply(func=dayi)]

                         time    open   close    high     low volume ticker
0   2020-01-02 07:00:00+00:00  159.00  159.00  159.00  159.00      2   MSFT
0   2020-01-02 07:03:00+00:00  158.35  158.35  158.35  158.35      1   MSFT
0   2020-01-02 07:06:00+00:00  158.42  158.56  158.56  158.42      2   MSFT
0   2020-01-02 07:07:00+00:00  158.56  158.56  158.56  158.56      7   MSFT
0   2020-01-02 07:08:00+00:00  158.56  158.56  158.56  158.56     40   MSFT
..                        ...     ...     ...     ...     ...    ...    ...
0   2020-01-02 22:37:00+00:00  160.75  160.75  160.75  160.75    275   MSFT
0   2020-01-02 22:38:00+00:00  160.75  160.75  160.75  160.75    109   MSFT
0   2020-01-02 22:39:00+00:00  160.75  160.75  160.75  160.75    164   MSFT
0   2020-01-02 22:41:00+00:00  160.75  160.75  160.75  160.75    250   MSFT
0   2020-01-02 22:42:00+00:00  160.65  160.65  160.65  160.65      2   MSFT

[637 rows x 7 columns]

In [21]:
from tinkoff.investments import TinkoffInvestmentsRESTClient, Environment

In [25]:
async with TinkoffInvestmentsRESTClient(
        token=token,
        environment=Environment.SANDBOX) as client:
    instruments = await client.market.instruments.search('GOOG')

In [26]:
instruments

[MarketInstrument(figi='BBG009S3NB30', ticker='GOOG', lot=1, name='Google', type=<InstrumentType.STOCK: 'Stock'>, currency=<Currency.USD: 'USD'>, isin='US02079K1079', minPriceIncrement=0.01)]

In [36]:
test_range = result.copy()
test_range['time'] = test_range['time'].dt.tz_convert('EST')
test_range

                        time    open   close    high     low volume ticker
0  2020-01-02 02:00:00-05:00  159.00  159.00  159.00  159.00      2   MSFT
0  2020-01-02 02:03:00-05:00  158.35  158.35  158.35  158.35      1   MSFT
0  2020-01-02 02:06:00-05:00  158.42  158.56  158.56  158.42      2   MSFT
0  2020-01-02 02:07:00-05:00  158.56  158.56  158.56  158.56      7   MSFT
0  2020-01-02 02:08:00-05:00  158.56  158.56  158.56  158.56     40   MSFT
..                       ...     ...     ...     ...     ...    ...    ...
0  2020-02-28 17:39:00-05:00  163.00  163.15  163.15  163.00      6   MSFT
0  2020-02-28 17:40:00-05:00  163.15  163.15  163.15  163.15     39   MSFT
0  2020-02-28 17:41:00-05:00  163.15  163.20  163.20  162.90    312   MSFT
0  2020-02-28 17:42:00-05:00  163.30  163.30  163.30  163.30     10   MSFT
0  2020-02-28 17:43:00-05:00  163.00  163.00  163.00  163.00      1   MSFT

[32259 rows x 7 columns]

In [37]:
test_range['to_holi'] = test_range['time'].apply(func=BusyDayExchange.to_holiday, args=(True,))
test_range['to_full'] = test_range['time'].apply(func=BusyDayExchange.to_fullday, args=(True,))
test_range['to_cut'] = test_range['time'].apply(func=BusyDayExchange.to_cutday, args=(True,))
test_range['af_holi'] = test_range['time'].apply(func=BusyDayExchange.to_holiday, args=(False,))
test_range['af_full'] = test_range['time'].apply(func=BusyDayExchange.to_fullday, args=(False,))
test_range['af_cut'] = test_range['time'].apply(func=BusyDayExchange.to_cutday, args=(False,))
test_range

,time,open,close,high,low,volume,ticker,to_holi,to_full,to_cut,af_holi,af_full,af_cut
0,2020-01-02 02:00:00-05:00,159.00,159.00,159.00,159.00,2,MSFT,17,1,329,-2,-1,-10
0,2020-01-02 02:03:00-05:00,158.35,158.35,158.35,158.35,1,MSFT,17,1,329,-2,-1,-10
0,2020-01-02 02:06:00-05:00,158.42,158.56,158.56,158.42,2,MSFT,17,1,329,-2,-1,-10
0,2020-01-02 02:07:00-05:00,158.56,158.56,158.56,158.56,7,MSFT,17,1,329,-2,-1,-10
0,2020-01-02 02:08:00-05:00,158.56,158.56,158.56,158.56,40,MSFT,17,1,329,-2,-1,-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2020-02-28 17:39:00-05:00,163.00,163.15,163.15,163.00,6,MSFT,41,1,272,-12,-1,-67
0,2020-02-28 17:40:00-05:00,163.15,163.15,163.15,163.15,39,MSFT,41,1,272,-12,-1,-67
0,2020-02-28 17:41:00-05:00,163.15,163.20,163.20,162.90,312,MSFT,41,1,272,-12,-1,-67
0,2020-02-28 17:42:00-05:00,163.30,163.30,163.30,163.30,10,MSFT,41,1,272,-12,-1,-67
0,2020-02-28 17:43:00-05:00,163.00,163.00,163.00,163.00,1,MSFT,41,1,272,-12,-1,-67